/**
 * Production SQL for the verified external programme listings:
 *   npx tsx scripts/affiliate-programs-sql.ts indian > indian-programs.sql
 *
 * Production data is changed through a reviewed SQL script run in the Supabase
 * SQL editor (docs/PRODUCTION.md §4d). The script is generated from the same
 * seed module the local seed uses, so the two cannot drift. It is idempotent:
 * a row is skipped when its slug, brand name or signup URL already exists
 * (including listings owned by brand accounts), and each audit entry is written
 * only together with the row it describes.
 */
import { createHash } from "node:crypto";
import { EXAMPLE_AFFILIATE_PROGRAMS, INDIAN_AFFILIATE_PROGRAMS, type ExampleAffiliateProgram } from "../prisma/seed-data/affiliate-programs";

const lit = (v: string | null | undefined) => (v == null ? "NULL" : `'${v.replace(/'/g, "''")}'`);
const num = (v: number | null | undefined) => (v == null ? "NULL" : String(v));
const arr = (xs: readonly string[], type: string) => (xs.length ? `ARRAY[${xs.map(lit).join(", ")}]::${type}[]` : `'{}'::${type}[]`);
const id = (prefix: string, slug: string) => `${prefix}_${createHash("sha256").update(slug).digest("hex").slice(0, 24)}`;

function rowSql(p: ExampleAffiliateProgram, seed: string): string {
  const at = `'${p.sources.checkedOn}T00:00:00.000Z'::timestamptz`;
  const bestFor = (p.bestFor as string[] | undefined) ?? [];
  const platforms = (p.supportedPlatforms as string[] | undefined) ?? [];
  return `-- ${p.brandName}: ${p.name}
WITH ins AS (
  INSERT INTO "affiliate_programs" (
    "id", "brandId", "brandName", "name", "slug", "programType", "description", "category", "subcategory", "bestFor", "featured",
    "websiteUrl", "programUrl", "signupUrl", "logoUrl", "commissionType", "commissionDescription", "cookieDurationDays", "networkName",
    "approvalType", "status", "minFollowers", "supportedPlatforms", "geography", "requirements", "subIdParam",
    "submittedAt", "reviewedAt", "verifiedAt", "sourceUrl", "createdAt", "updatedAt"
  )
  SELECT
    ${lit(id("aff", p.slug))}, NULL, ${lit(p.brandName)}, ${lit(p.name)}, ${lit(p.slug)}, ${lit(p.programType as string)}::"AffiliateProgramType",
    ${lit(p.description)}, ${lit(p.category)}, ${lit(p.subcategory)}, ${arr(bestFor, "text")}, false,
    ${lit(p.websiteUrl)}, ${lit(p.programUrl)}, ${lit(p.signupUrl)}, ${lit(p.logoUrl)},
    ${p.commissionType ? `${lit(p.commissionType as string)}::"AffiliateCommissionType"` : "NULL"}, ${lit(p.commissionDescription)},
    ${num(p.cookieDurationDays)}, ${lit(p.networkName)},
    NULL, 'APPROVED'::"AffiliateProgramStatus", NULL, ${arr(platforms, '"SocialPlatform"')}, ${lit(p.geography)}, ${lit(p.requirements)}, NULL,
    ${at}, ${at}, ${at}, ${lit(p.sourceUrl)}, now(), now()
  WHERE NOT EXISTS (
    SELECT 1 FROM "affiliate_programs" a LEFT JOIN "brands" b ON b."id" = a."brandId"
    WHERE a."slug" = ${lit(p.slug)}
       OR (a."status" <> 'CLOSED' AND (lower(a."brandName") = lower(${lit(p.brandName)}) OR lower(b."name") = lower(${lit(p.brandName)}) OR a."signupUrl" = ${lit(p.signupUrl)}))
  )
  RETURNING "id"
)
INSERT INTO "audit_logs" ("id", "userId", "action", "entityType", "entityId", "metadata", "createdAt")
SELECT ${lit(id("aud", p.slug))}, NULL, 'AFFILIATE_PROGRAM_CREATED', 'AffiliateProgram', ins."id",
       jsonb_build_object('byAdmin', true, 'curated', true, 'seed', ${lit(seed)}, 'checkedOn', ${lit(p.sources.checkedOn)}), now()
FROM ins;
`;
}

const which = process.argv[2] ?? "indian";
const rows = which === "global" ? EXAMPLE_AFFILIATE_PROGRAMS : INDIAN_AFFILIATE_PROGRAMS;
const seed = which === "global" ? "verified-programs" : "verified-indian-programs";

process.stdout.write(`-- Refnivo: ${rows.length} verified external programme listings (${which}).
-- Generated by scripts/affiliate-programs-sql.ts from prisma/seed-data. Safe to run more than once:
-- existing slugs, brand names and signup URLs are skipped, nothing is updated or deleted.
BEGIN;

${rows.map((p) => rowSql(p, seed)).join("\n")}
-- Check: how many of these listings now exist.
SELECT count(*) AS listed FROM "affiliate_programs" WHERE "slug" IN (${rows.map((p) => lit(p.slug)).join(", ")});

COMMIT;
`);
