import type { AffiliateProgramEntry } from "./affiliate-programs";

/**
 * 100 verified Indian external programmes — affiliate, creator, influencer,
 * partner and customer-referral schemes run by Indian brands outside Refnivo.
 *
 * Same rules as the global list (see affiliate-programs.ts): every programme was
 * checked live on its official page on `checkedOn` — the brand's own site, its
 * official affiliate portal (GoAffPro / UpPromote / Shopify Collabs), or its
 * official listing on the Admitad India network. Only facts published there are
 * stored. Where sources disagree on a rate, the commission is left unstated.
 * Rejected during checking (not listed): programmes whose portal said
 * "disabled" or "discontinued" (e.g. Pee Safe, Specsmakers, Baybee, Slurrp Farm,
 * Sleepy Owl, Mittal Teas), pages with no programme content, non-Indian brands,
 * and network pages that turned out to be auto-generated (INRDeals, Cuelinks).
 *
 * Logos live in public/brand-logos/<logo>.png: each brand's own site logo or
 * icon, or the logo file on its Wikipedia infobox, made square.
 */
const CHECKED = "2026-10-01";

export const INDIAN_ENTRIES: AffiliateProgramEntry[] = [
  {
    slug: "chumbak-affiliate-program",
    brandName: "Chumbak",
    name: "#WithChumbak Affiliate Program",
    programType: "CREATOR_AFFILIATE",
    category: "Lifestyle",
    subcategory: "Home decor & accessories",
    description:
      "Chumbak is an Indian lifestyle brand known for colourful home decor, bags, accessories and gifts. The #WithChumbak Affiliate Program invites content creators to promote Chumbak; partners earn a share of revenue whenever their exclusive discount code is used on a purchase on Chumbak's website.",
    websiteUrl: "https://www.chumbak.com",
    programUrl: "https://www.chumbak.com/pages/affiliate-program",
    requirements: "Social media enthusiasts and content creators who are fans of the brand; applications are reviewed.",
    geography: "India",
    bestFor: ["Lifestyle creators", "Home creators"],
    logo: "chumbak",
    sources: { checkedOn: CHECKED, urls: ["https://www.chumbak.com/pages/affiliate-program"], notes: "Official FAQ: share of revenue on purchases using the partner's exclusive code; rate not stated." },
  },
  {
    slug: "offduty-affiliate-program",
    brandName: "Offduty",
    name: "Offduty Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Streetwear",
    description:
      "Offduty is an Indian streetwear label selling casual clothing and essentials. Its affiliate program has no entry requirement: you email the brand to join, receive a dashboard to track earnings, and earn a commission on every order completed through your link.",
    websiteUrl: "https://offduty.in",
    programUrl: "https://offduty.in/pages/affiliate-program",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% on every completed order",
    requirements: "No requirement to join; email the brand to have an affiliate account created.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "offduty",
    sources: { checkedOn: CHECKED, urls: ["https://offduty.in/pages/affiliate-program"], notes: "'For every order completed through your link, you will receive 10% commission.'" },
  },
  {
    slug: "clovia-affiliate-program",
    brandName: "Clovia",
    name: "Clovia Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Lingerie & loungewear",
    description:
      "Clovia is an Indian lingerie, loungewear and activewear brand. Its Partner with Clovia page offers an affiliate option for website owners alongside a Girl Tribe programme for fashion influencers; you choose the option that suits you and apply on Clovia's site.",
    websiteUrl: "https://www.clovia.com",
    programUrl: "https://www.clovia.com/become-an-affiliate/",
    requirements: "Website owners can apply as affiliates; fashion influencers can apply to the Girl Tribe programme.",
    geography: "India",
    bestFor: ["Fashion creators", "Lifestyle creators"],
    logo: "clovia",
    sources: { checkedOn: CHECKED, urls: ["https://www.clovia.com/become-an-affiliate/"], notes: "Partner page lists AFFILIATE (website owners) and Girl Tribe (influencers); commission not stated." },
  },
  {
    slug: "colorbar-affiliate-program",
    brandName: "Colorbar",
    name: "Colorbar Affiliate Program",
    programType: "CREATOR_AFFILIATE",
    category: "Beauty",
    subcategory: "Makeup",
    description:
      "Colorbar is an Indian makeup and cosmetics brand. The Colorbar Affiliate Program gives creators an exclusive affiliate code that gives their followers a 20% discount on any Colorbar product, with a commission on the order value that rises with monthly net sales.",
    websiteUrl: "https://colorbarcosmetics.com",
    programUrl: "https://colorbarcosmetics.com/pages/colorbar-affiliate-program",
    commissionType: "VARIES",
    commissionDescription: "4%–8% by net sales slab (your audience gets 20% off)",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "colorbar",
    sources: { checkedOn: CHECKED, urls: ["https://colorbarcosmetics.com/pages/colorbar-affiliate-program"], notes: "Slabs: Rs 50,000 → 4%, Rs 75,000 → 6%, Rs 1,00,000 → 8%; consumers get 20% off." },
  },
  {
    slug: "mars-cosmetics-affiliate-creator-program",
    brandName: "MARS Cosmetics",
    name: "MARS Affiliate Creator Program",
    programType: "CREATOR_AFFILIATE",
    category: "Beauty",
    subcategory: "Makeup",
    description:
      "MARS Cosmetics is an Indian makeup brand. Its Affiliate Creator Program gives you a unique code that offers your audience a flat 15% off on orders above ₹499, while you earn a tiered commission on the eligible sales your content generates.",
    websiteUrl: "https://marscosmetics.in",
    programUrl: "https://marscosmetics.in/pages/affiliate-creator",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% (tiered, from 5% by monthly net order value)",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "mars-cosmetics",
    sources: { checkedOn: CHECKED, urls: ["https://marscosmetics.in/pages/affiliate-creator"], notes: "'Earn up to 10% commission'; Starter 5% below ₹50,000 monthly; audience gets 15% off above ₹499." },
  },
  {
    slug: "fixderma-affiliate-program",
    brandName: "Fixderma",
    name: "Fixderma Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Skincare",
    description:
      "Fixderma is an Indian dermatologist-focused skincare brand. Its affiliate program, run on GoAffPro, provides linking tools for marketplaces, content sites, influencers and bloggers, and pays a commission on all qualifying purchases from your referrals.",
    websiteUrl: "https://www.fixderma.com",
    programUrl: "https://www.fixderma.com/pages/become-an-affiliate",
    signupUrl: "https://fixderma-skincare.goaffpro.com/create-account",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 5% on qualifying purchases",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "fixderma",
    sources: { checkedOn: CHECKED, urls: ["https://www.fixderma.com/pages/become-an-affiliate", "https://fixderma-skincare.goaffpro.com/"], notes: "Brand page and live portal: 'Earn up to 5% in commissions'." },
  },
  {
    slug: "nutrabay-partner-program",
    brandName: "Nutrabay",
    name: "Nutrabay Partner Program",
    programType: "AFFILIATE",
    category: "Fitness",
    subcategory: "Sports nutrition",
    description:
      "Nutrabay is an Indian online store for sports nutrition and health supplements that also sells its own Nutrabay brand products. The Nutrabay Partner Program pays a commission on Nutrabay brand products bought through your link, with monthly payouts and no registration fee.",
    websiteUrl: "https://nutrabay.com",
    programUrl: "https://nutrabay.com/affiliates",
    signupUrl: "https://nutrabay.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% on Nutrabay brand products",
    cookieDurationDays: 30,
    geography: "India",
    bestFor: ["Fitness creators"],
    logo: "nutrabay",
    sources: { checkedOn: CHECKED, urls: ["https://nutrabay.com/affiliates", "https://nutrabay.goaffpro.com/"], notes: "'Earn 10% in commissions'; Nutrabay brand products only; cookie stored for 30 days; portal live." },
  },
  {
    slug: "salty-collabs",
    brandName: "Salty",
    name: "Salty Collabs Program",
    programType: "CREATOR_AFFILIATE",
    category: "Fashion",
    subcategory: "Jewellery & accessories",
    description:
      "Salty is an Indian fashion jewellery and accessories brand. Its creator collaboration page, powered by Shopify Collabs, lists affiliate marketing, gifting, discount codes, content creation and campaign opportunities for creators who apply to partner with the brand.",
    websiteUrl: "https://salty.co.in",
    programUrl: "https://salty.co.in/pages/collabs",
    networkName: "Shopify Collabs",
    geography: "India",
    bestFor: ["Fashion creators", "Lifestyle creators"],
    logo: "salty",
    sources: { checkedOn: CHECKED, urls: ["https://salty.co.in/pages/collabs"], notes: "Shopify Collabs page: affiliate marketing, gifting, discount codes; rates not stated." },
  },
  {
    slug: "isharya-affiliate-program",
    brandName: "Isharya",
    name: "Isharya Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Designer jewellery",
    description:
      "Isharya is an Indian designer fashion jewellery brand. Its affiliate program is offered through the ShareASale and Refersion networks, letting website owners sign up and earn commission payments on sales referred from their sites.",
    websiteUrl: "https://isharya.com",
    programUrl: "https://isharya.com/pages/affiliates",
    networkName: "ShareASale / Refersion",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "isharya",
    sources: { checkedOn: CHECKED, urls: ["https://isharya.com/pages/affiliates"], notes: "'Isharya has teamed up with Share-a-Sale and Refersion'; rate not stated." },
  },
  {
    slug: "superbottoms-affiliate-program",
    brandName: "SuperBottoms",
    name: "SuperBottoms Affiliate Program",
    programType: "AFFILIATE",
    category: "Baby Products",
    subcategory: "Cloth diapers",
    description:
      "SuperBottoms is an Indian brand of cloth diapers and sustainable baby and kids products designed by mothers. Its affiliate program gives you a unique link to promote the range and pays a commission on purchases made through it.",
    websiteUrl: "https://superbottoms.com",
    programUrl: "https://superbottoms.com/pages/affiliate-program",
    signupUrl: "https://superbottoms.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% per purchase via your link",
    geography: "India",
    bestFor: ["Parenting creators"],
    logo: "superbottoms",
    sources: { checkedOn: CHECKED, urls: ["https://superbottoms.com/pages/affiliate-program", "https://superbottoms.goaffpro.com/"], notes: "'Earn up to 10% commission every time a purchase is done via your unique link'; portal live." },
  },
  {
    slug: "fnp-affiliate-program",
    brandName: "Ferns N Petals",
    name: "FNP Affiliate Program",
    programType: "AFFILIATE",
    category: "Other",
    subcategory: "Gifting & flowers",
    description:
      "Ferns N Petals (FNP) is an Indian gifting company selling flowers, cakes, plants and gifts. The FNP Affiliate Program pays a commission on sales generated through your platform, with monthly payments and promotional creatives; you join by contacting FNP's affiliate team.",
    websiteUrl: "https://www.fnp.com",
    programUrl: "https://www.fnp.com/info/affiliate-program",
    commissionType: "VARIES",
    commissionDescription: "7%–10% per sale",
    cookieDurationDays: 1,
    requirements: "Contact the FNP affiliate team to become a partner.",
    geography: "India",
    bestFor: ["Lifestyle creators", "General creators"],
    logo: "ferns-n-petals",
    sources: { checkedOn: CHECKED, urls: ["https://www.fnp.com/info/affiliate-program"], notes: "'commission of 7-10% on each sale'; '1 day cookie period'." },
  },
  {
    slug: "winni-affiliate-program",
    brandName: "Winni",
    name: "Winni Affiliate Program",
    programType: "AFFILIATE",
    category: "Other",
    subcategory: "Cakes & gifting",
    description:
      "Winni is an Indian online gifting company delivering cakes, flowers and personalised gifts. Its affiliate program pays a commission on every sale generated from your platform, with monthly payments and linking tools; you join by emailing Winni's affiliate team.",
    websiteUrl: "https://www.winni.in",
    programUrl: "https://www.winni.in/affiliate",
    commissionType: "VARIES",
    commissionDescription: "8%–10% per sale",
    requirements: "Email the Winni affiliate team to join.",
    geography: "India",
    bestFor: ["Lifestyle creators", "Food creators"],
    logo: "winni",
    sources: { checkedOn: CHECKED, urls: ["https://www.winni.in/affiliate"], notes: "'commission of 8-10% on every single sale'." },
  },
  {
    slug: "nestasia-designer-affiliate-program",
    brandName: "Nestasia",
    name: "Nestasia Designer Affiliate Program (NestDAP)",
    programType: "PARTNER",
    category: "Home",
    subcategory: "Home decor & tableware",
    description:
      "Nestasia is an Indian home decor, tableware and kitchenware brand. NestDAP, its Designer Affiliate Program, is a trade programme for architects, interior designers, design studios and stylists, who register with business details and track rewards in a member dashboard.",
    websiteUrl: "https://nestasia.in",
    programUrl: "https://nestasia.in/pages/interior-designers-program",
    requirements: "Architects, interior designers, design studios and stylists; registration needs company details and GST number.",
    geography: "India",
    bestFor: ["Home creators"],
    logo: "nestasia",
    sources: { checkedOn: CHECKED, urls: ["https://nestasia.in/pages/interior-designers-program"], notes: "Trade programme; commission transferred to members; rate not stated." },
  },
  {
    slug: "tahvo-affiliate-program",
    brandName: "Tahvo",
    name: "Tahvo India Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Men's ethnic wear",
    description:
      "Tahvo is an Indian men's ethnic and occasion wear brand. Its affiliate program invites Instagram influencers, YouTubers, fashion bloggers and stylists to earn commission on sales through their link or code, with a tracking dashboard and monthly payouts via UPI or bank.",
    websiteUrl: "https://www.tahvoindia.com",
    programUrl: "https://www.tahvoindia.com/pages/join-as-an-affiliate",
    signupUrl: "https://af.uppromote.com/deevo-in/register",
    networkName: "UpPromote",
    cookieDurationDays: 30,
    requirements: "Fashion and lifestyle influencers, bloggers and stylists.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "tahvo",
    sources: { checkedOn: CHECKED, urls: ["https://www.tahvoindia.com/pages/join-as-an-affiliate", "https://af.uppromote.com/deevo-in/register"], notes: "Brand page says 10–15%; registration form shows 20% in terms and 0% in the field — rates conflict, so commission is left unstated. 30-day cookie on the form." },
  },
  {
    slug: "skinbae-affiliate-program",
    brandName: "Skinbae",
    name: "Skinbae Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "K-beauty retail",
    description:
      "Skinbae is an Indian online destination for authentic Korean beauty products. Its affiliate program invites content creators, beauty bloggers, YouTubers and skincare reviewers to share products with a unique referral link or code and earn a commission on each sale.",
    websiteUrl: "https://www.skinbae.in",
    programUrl: "https://www.skinbae.in/pages/affiliate-program",
    signupUrl: "https://skinbae.goaffpro.com/",
    networkName: "GoAffPro",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "skinbae",
    sources: { checkedOn: CHECKED, urls: ["https://www.skinbae.in/pages/affiliate-program", "https://skinbae.goaffpro.com/"], notes: "Brand page says 5% / up to 7.5%; portal says 10% — rates conflict, so commission is left unstated." },
  },
  {
    slug: "dreamyderma-affiliate-program",
    brandName: "DreamyDerma",
    name: "DreamyDerma Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Skincare retail",
    description:
      "DreamyDerma is an Indian online store for skincare and beauty products. Its affiliate program lets anyone share products through a personal link: shoppers get 5% off their order, and the affiliate earns a percentage of total monthly eligible sales.",
    websiteUrl: "https://dreamyderma.com",
    programUrl: "https://dreamyderma.com/pages/affiliate-program",
    signupUrl: "https://dreamyderma.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "PERCENTAGE",
    commissionDescription: "3% of monthly eligible sales (shoppers get 5% off)",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "dreamyderma",
    sources: { checkedOn: CHECKED, urls: ["https://dreamyderma.com/pages/affiliate-program", "https://dreamyderma.goaffpro.com/"], notes: "'You earn 3% of your total monthly eligible sales'; portal live." },
  },
  {
    slug: "paksha-affiliate-program",
    brandName: "Paksha",
    name: "Paksha Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Silver jewellery",
    description:
      "Paksha is an Indian brand of handcrafted silver jewellery rooted in traditional techniques. Its affiliate program pays a commission on net sales made through your affiliate link or coupon code, with newsletters on upcoming campaigns and custom promo codes on request.",
    websiteUrl: "https://paksha.com",
    programUrl: "https://paksha.com/pages/paksha-affiliates",
    signupUrl: "https://af.uppromote.com/paksha-store/register",
    networkName: "UpPromote",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% of net referral sales",
    cookieDurationDays: 30,
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "paksha",
    sources: { checkedOn: CHECKED, urls: ["https://paksha.com/pages/paksha-affiliates", "https://af.uppromote.com/paksha-store/register"], notes: "Registration form: 30 cookie days, 10% of net sales." },
  },
  {
    slug: "silvish-affiliate-program",
    brandName: "Silvish",
    name: "Silvish India Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Silver jewellery",
    description:
      "Silvish is an Indian silver jewellery brand. The Silvish India Affiliate Club invites fashion influencers and jewellery enthusiasts to share a unique affiliate link and earn commissions, with access to exclusive discounts and early product launches.",
    websiteUrl: "https://www.silvish.co",
    programUrl: "https://www.silvish.co/pages/join-silvish-india-affiliate-program",
    signupUrl: "https://188d89-2.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% per referral",
    requirements: "Commission can be redeemed once it reaches ₹500.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "silvish",
    sources: { checkedOn: CHECKED, urls: ["https://www.silvish.co/pages/join-silvish-india-affiliate-program", "https://188d89-2.goaffpro.com/"], notes: "Portal: 'Earn up to 10% commission'; ₹500 redemption minimum." },
  },
  {
    slug: "beadsnfashion-creator-affiliate-program",
    brandName: "BeadsnFashion",
    name: "BeadsnFashion Creator & Affiliate Program",
    programType: "CREATOR_AFFILIATE",
    category: "Lifestyle",
    subcategory: "Jewellery making & DIY crafts",
    description:
      "BeadsnFashion is an Indian supplier of jewellery-making and DIY craft materials, trading since 1996. Its Creator & Affiliate Program is open to content creators, jewellery designers, craft instructors and hobbyists, who earn a commission on eligible completed orders through their creator links.",
    websiteUrl: "https://www.beadsnfashion.com",
    programUrl: "https://www.beadsnfashion.com/pages/affiliate-program",
    signupUrl: "https://beadsnfashionnn.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% on eligible completed orders",
    cookieDurationDays: 30,
    requirements: "Minimum payout ₹500; paid via UPI or bank transfer.",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "beadsnfashion",
    sources: { checkedOn: CHECKED, urls: ["https://www.beadsnfashion.com/pages/affiliate-program", "https://beadsnfashionnn.goaffpro.com/"], notes: "'Earn 10% Commission on Eligible Completed Orders, 30-Day Cookie Tracking'." },
  },
  {
    slug: "indya-affiliate-program",
    brandName: "Indya",
    name: "Indya Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Ethnic wear",
    description:
      "Indya (House of Indya) is an Indian ethnic and fusion wear brand for women and kids. Its affiliate program lets you refer Indya products through your code or affiliate webshop and earn a commission on every sale; the team verifies your social profiles after you register.",
    websiteUrl: "https://www.houseofindya.com",
    programUrl: "https://www.houseofindya.com/affiliatescontactus",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% on sales via your code or webshop",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "indya",
    sources: { checkedOn: CHECKED, urls: ["https://www.houseofindya.com/affiliatescontactus"], notes: "'you will earn a commission of 10%'." },
  },
  {
    slug: "tistabene-affiliate-program",
    brandName: "Tistabene",
    name: "Tistabene Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Women's ethnic wear",
    description:
      "Tistabene is an Indian women's ethnic and fusion wear brand. Its affiliate programme, which the brand also calls Refer and Earn, lets you promote products to your audience, friends and family and earn a commission on their purchases, with no fixed hours.",
    websiteUrl: "https://www.tistabene.com",
    programUrl: "https://www.tistabene.com/pages/become-an-affiliates",
    signupUrl: "https://tistab.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% per referral",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "tistabene",
    sources: { checkedOn: CHECKED, urls: ["https://www.tistabene.com/pages/become-an-affiliates", "https://tistab.goaffpro.com/"], notes: "Brand page: 10%; portal: 'up to 10%'." },
  },
  {
    slug: "anveshan-affiliate-program",
    brandName: "Anveshan",
    name: "Anveshan Affiliate Program",
    programType: "AFFILIATE",
    category: "Food",
    subcategory: "Ghee, oils & staples",
    description:
      "Anveshan is an Indian farm-to-home food brand selling A2 ghee, cold-pressed oils, honey and staples. Its affiliate program invites creators and influencers to apply, receive a personal coupon code that gives shoppers a discount, and earn a commission on every order using it.",
    websiteUrl: "https://www.anveshan.farm",
    programUrl: "https://www.anveshan.farm/pages/affiliate",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% minimum commission (shoppers get 22% off)",
    geography: "India",
    bestFor: ["Food creators"],
    logo: "anveshan",
    sources: { checkedOn: CHECKED, urls: ["https://www.anveshan.farm/pages/affiliate"], notes: "'10% Minimum Commission, 22% Coupon Code Discount'." },
  },
  {
    slug: "kindlife-kind-champion",
    brandName: "Kind Life",
    name: "Kind Champion Creator Program",
    programType: "CREATOR_AFFILIATE",
    category: "Beauty",
    subcategory: "Beauty marketplace",
    description:
      "Kind Life is an Indian online store for Korean and global beauty, skincare and health brands. Its Kind Champion program gives creators an affiliate page and link with a commission on every order, plus tiered paid deliverables and free samples for qualifying creators.",
    websiteUrl: "https://www.kindlife.in",
    programUrl: "https://www.kindlife.in/kind-champion/",
    commissionType: "PERCENTAGE",
    commissionDescription: "8% on orders through your link",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "kind-life",
    sources: { checkedOn: CHECKED, urls: ["https://www.kindlife.in/kind-champion/"], notes: "'8% commission on every order through your link'; tiered payouts ₹3,000–₹10,000 for deliverables." },
  },
  {
    slug: "redgem-affiliate-program",
    brandName: "Redgem",
    name: "Redgem Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Silver & gemstone jewellery",
    description:
      "Redgem is an Indian brand of silver and natural gemstone jewellery. The Redgem Affiliate Program is free to join and pays a commission on every sale made through your referral link when you promote its rings, earrings, pendants and jewellery sets.",
    websiteUrl: "https://redgemindia.com",
    programUrl: "https://redgemindia.com/jewelry-affiliate-program-faq",
    commissionType: "PERCENTAGE",
    commissionDescription: "5% per sale via your referral link",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "redgem",
    sources: { checkedOn: CHECKED, urls: ["https://redgemindia.com/jewelry-affiliate-program-faq"], notes: "'Affiliates earn a generous 5% commission on every sale'." },
  },
  {
    slug: "online-indian-furniture-affiliate-program",
    brandName: "Online Indian Furniture",
    name: "Online Indian Furniture Affiliate Program",
    programType: "AFFILIATE",
    category: "Home",
    subcategory: "Handmade furniture",
    description:
      "Online Indian Furniture sells luxury handmade Indian furniture and home decor with delivery across India. Its affiliate program offers a real-time dashboard to track clicks, sales and commissions on confirmed sales referred by creators and publishers.",
    websiteUrl: "https://www.onlineindianfurniture.in",
    programUrl: "https://www.onlineindianfurniture.in/affiliate-program/",
    commissionType: "VARIES",
    commissionDescription: "Up to 15% per confirmed sale",
    geography: "India",
    bestFor: ["Home creators"],
    logo: "online-indian-furniture",
    sources: { checkedOn: CHECKED, urls: ["https://www.onlineindianfurniture.in/affiliate-program/"], notes: "'Earn up to 15% commission per confirmed sale'." },
  },
  {
    slug: "miko-creator-program",
    brandName: "Miko",
    name: "Miko Creator Program",
    programType: "INFLUENCER",
    category: "Baby Products",
    subcategory: "Kids' AI robots",
    description:
      "Miko is an Indian company that makes AI-powered companion robots for children's learning and play. The Miko Creator Program invites parenting, fashion and tech creators to apply through a form on Miko's site, including for barter collaborations.",
    websiteUrl: "https://miko.ai",
    programUrl: "https://miko.ai/pages/creator-program",
    requirements: "Application form asks for Instagram profile, follower count and openness to barter collaborations.",
    geography: "India",
    bestFor: ["Parenting creators", "Tech creators"],
    logo: "miko",
    sources: { checkedOn: CHECKED, urls: ["https://miko.ai/pages/creator-program"], notes: "Creator application form; barter collaborations; no commission stated." },
  },
  {
    slug: "house-of-beauty-india-affiliate-program",
    brandName: "House of Beauty India",
    name: "House of Beauty Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Cosmetics",
    description:
      "House of Beauty India (HOB) is an Indian cosmetics and personal care brand. Its affiliate program, run on GoAffPro, provides linking tools for networks, content sites, influencers and bloggers and pays a commission on all qualifying purchases from your referrals.",
    websiteUrl: "https://houseofbeautyindia.com",
    programUrl: "https://affiliateshouseofbeautyindia.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 20% per successful referral",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "house-of-beauty-india",
    sources: { checkedOn: CHECKED, urls: ["https://affiliateshouseofbeautyindia.goaffpro.com/", "https://houseofbeautyindia.com/pages/affiliate-policy-hob"], notes: "Portal (©houseofbeautyindia.com): 'Earn up to 20% commission'." },
  },
  {
    slug: "kiro-influencer-program",
    brandName: "Kiro",
    name: "Kiro Influencer Program",
    programType: "INFLUENCER",
    category: "Beauty",
    subcategory: "Clean makeup",
    description:
      "Kiro is an Indian clean, vegan makeup brand. Its influencer program page invites creators to apply with their Instagram follower count and location through a form on Kiro's site; the brand reviews applications for collaborations.",
    websiteUrl: "https://kirobeauty.com",
    programUrl: "https://kirobeauty.com/pages/influencer-program",
    requirements: "Application form asks for Instagram follower count and location.",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "kiro",
    sources: { checkedOn: CHECKED, urls: ["https://kirobeauty.com/pages/influencer-program"], notes: "Influencer application form; terms not stated." },
  },
  {
    slug: "menhood-influencer-program",
    brandName: "Menhood",
    name: "Team Menhood Influencer Program",
    programType: "INFLUENCER",
    category: "Personal Care",
    subcategory: "Men's grooming",
    description:
      "Menhood is an Indian men's grooming brand known for its intimate-area trimmer and grooming products. Its Become a Menhood Influencer page invites creators to join #TeamMenhood and get rewarded, with applications taken through an embedded form.",
    websiteUrl: "https://menhood.in",
    programUrl: "https://menhood.in/pages/become-an-influencer",
    requirements: "Apply through the form on the page.",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "menhood",
    sources: { checkedOn: CHECKED, urls: ["https://menhood.in/pages/become-an-influencer"], notes: "'Become a Menhood Influencer and Get Rewarded'; Airtable application; terms not stated." },
  },
  {
    slug: "india-circus-influencer-programme",
    brandName: "India Circus",
    name: "India Circus Influencer Programme",
    programType: "INFLUENCER",
    category: "Home",
    subcategory: "Home decor & lifestyle",
    description:
      "India Circus is an Indian design brand selling home decor, furnishings, tableware, wallpapers and accessories with bold, India-inspired prints. Its influencer programme page takes applications from creators through a form for collaborations.",
    websiteUrl: "https://indiacircus.com",
    programUrl: "https://indiacircus.com/influencer-programme",
    requirements: "Complete the form on the influencer programme page.",
    geography: "India",
    bestFor: ["Home creators", "Lifestyle creators"],
    logo: "india-circus",
    sources: { checkedOn: CHECKED, urls: ["https://indiacircus.com/influencer-programme"], notes: "Influencer programme enquiry form; terms not stated." },
  },
  {
    slug: "jiva-ayurveda-affiliate-program",
    brandName: "Jiva Ayurveda",
    name: "Jiva Ayurveda Affiliate Program",
    programType: "AFFILIATE",
    category: "Personal Care",
    subcategory: "Ayurveda & wellness",
    description:
      "Jiva Ayurveda is an Indian Ayurvedic healthcare company offering consultations, medicines and wellness products. Its partner page invites organisations and individuals interested in becoming affiliates to fill out an affiliate application form.",
    websiteUrl: "https://www.jiva.com",
    programUrl: "https://www.jiva.com/affiliate",
    requirements: "Organisations and individuals apply through the affiliate application form.",
    geography: "India",
    bestFor: ["Lifestyle creators", "General creators"],
    logo: "jiva-ayurveda",
    sources: { checkedOn: CHECKED, urls: ["https://www.jiva.com/affiliate"], notes: "'If you are interested in becoming our affiliate, please fill out our Affiliate Application Form'; terms not stated." },
  },
  {
    slug: "justwravel-campus-ambassador-program",
    brandName: "JustWravel",
    name: "JustWravel Campus Ambassador Program",
    programType: "INFLUENCER",
    category: "Travel",
    subcategory: "Group trips",
    description:
      "JustWravel is an Indian travel company running group trips, treks and backpacking tours. Its Campus Ambassador Program lets students represent the brand on campus, earn rewards and pocket money, and receive certificates of recognition for their work.",
    websiteUrl: "https://www.justwravel.com",
    programUrl: "https://www.justwravel.com/campus-ambassador-program",
    requirements: "College students; applications through the programme page.",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "justwravel",
    sources: { checkedOn: CHECKED, urls: ["https://www.justwravel.com/campus-ambassador-program"], notes: "Campus ambassador programme with rewards and certificates; no commission rate stated." },
  },
  {
    slug: "world-of-perfumers-creator-collaborations",
    brandName: "World of Perfumers",
    name: "World of Perfumers Creator Collaborations",
    programType: "INFLUENCER",
    category: "Beauty",
    subcategory: "Fragrances & attars",
    description:
      "World of Perfumers is an Indian artisan fragrance brand selling perfumes and alcohol-free attars. Its collaboration page invites creators of every follower size to apply for gifting, paid collaborations, brand ambassador programmes, store visits and barter arrangements.",
    websiteUrl: "https://worldofperfumers.com",
    programUrl: "https://worldofperfumers.com/pages/influencer-collaboration-perfume-brand-india",
    requirements: "Creators of any follower size; submit the collaboration enquiry form.",
    geography: "India",
    bestFor: ["Beauty creators", "Lifestyle creators"],
    logo: "world-of-perfumers",
    sources: { checkedOn: CHECKED, urls: ["https://worldofperfumers.com/pages/influencer-collaboration-perfume-brand-india"], notes: "Gifting, paid collabs, ambassador and barter formats; no commission stated." },
  },
  {
    slug: "indiagift-affiliate-program",
    brandName: "Indiagift",
    name: "Indiagift Affiliate Program",
    programType: "AFFILIATE",
    category: "Other",
    subcategory: "Gifting",
    description:
      "Indiagift is an Indian online gifting store selling personalised and occasion gifts. Its affiliate program pays a commission on every purchase referred through banners, offers, coupons or links placed on your website; you join by emailing the brand.",
    websiteUrl: "https://www.indiagift.in",
    programUrl: "https://www.indiagift.in/affiliate",
    commissionType: "PERCENTAGE",
    commissionDescription: "Flat 10% on every purchase",
    requirements: "Email Indiagift to join.",
    geography: "India",
    bestFor: ["General creators"],
    logo: "indiagift",
    sources: { checkedOn: CHECKED, urls: ["https://www.indiagift.in/affiliate"], notes: "'Earn flat 10% flat commission on every purchase'." },
  },
  {
    slug: "fytika-collabs",
    brandName: "Fytika",
    name: "Fytika Creator Community",
    programType: "CREATOR_AFFILIATE",
    category: "Personal Care",
    subcategory: "Health & wellness",
    description:
      "Fytika Healthcare Products is an Indian brand of health and wellness products. Its creator community, run on Shopify Collabs, offers affiliate commission, discount codes, gifting, campaigns and content-creation opportunities to creators who apply.",
    websiteUrl: "https://fytika.com",
    programUrl: "https://fytika.com/pages/affiliates",
    networkName: "Shopify Collabs",
    geography: "India",
    bestFor: ["Fitness creators", "Lifestyle creators"],
    logo: "fytika",
    sources: { checkedOn: CHECKED, urls: ["https://fytika.com/pages/affiliates"], notes: "'From affiliate commission to gifting'; rates not stated." },
  },
  {
    slug: "freemen-affiliate-program",
    brandName: "Freemen",
    name: "Freemen Influencer Affiliate Program",
    programType: "CREATOR_AFFILIATE",
    category: "Fashion",
    subcategory: "One-gram gold jewellery",
    description:
      "Freemen is an Indian brand of one-gram gold jewellery. Its influencer affiliate program gives Instagram creators, YouTubers, resellers and WhatsApp communities a unique link and optional coupon, with a dashboard and UPI or bank payouts on tracked orders.",
    websiteUrl: "https://freemen.in",
    programUrl: "https://affiliate.freemen.in/",
    commissionType: "VARIES",
    commissionDescription: "From 6%, tiered by monthly sales",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "freemen",
    sources: { checkedOn: CHECKED, urls: ["https://affiliate.freemen.in/"], notes: "Tier table: Starter (any sales) 6%; higher tiers by monthly sales; returns-adjusted earnings." },
  },
  {
    slug: "luxurion-world-affiliate-program",
    brandName: "Luxurion World",
    name: "Luxurion World Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Handloom",
    description:
      "Luxurion World is an Indian brand of handloom and handcrafted heirloom textiles. Its affiliate program lets bloggers, social media creators and website owners promote its products with a unique affiliate link and earn a commission on every referred sale.",
    websiteUrl: "https://www.luxurionworld.com",
    programUrl: "https://www.luxurionworld.com/pages/affiliate-program",
    geography: "India",
    bestFor: ["Fashion creators", "Lifestyle creators"],
    logo: "luxurion-world",
    sources: { checkedOn: CHECKED, urls: ["https://www.luxurionworld.com/pages/affiliate-program"], notes: "Commission on every referred sale; rate not stated." },
  },
  {
    slug: "my-little-moppet-affiliate-program",
    brandName: "My Little Moppet",
    name: "My Little Moppet Affiliate Program",
    programType: "AFFILIATE",
    category: "Baby Products",
    subcategory: "Kids' food",
    description:
      "My Little Moppet is an Indian brand of fresh, nutritious food products for babies and children. Its affiliate program looks for content-focused influencers who engage expecting and new parents, with an affiliate dashboard and a dedicated management team.",
    websiteUrl: "https://shop.mylittlemoppet.com",
    programUrl: "https://shop.mylittlemoppet.com/affiliate-program-india/",
    commissionType: "PERCENTAGE",
    commissionDescription: "20% on sales via your link",
    cookieDurationDays: 30,
    geography: "India",
    bestFor: ["Parenting creators", "Food creators"],
    logo: "my-little-moppet",
    sources: { checkedOn: CHECKED, urls: ["https://shop.mylittlemoppet.com/affiliate-program-india/"], notes: "'20% Commission, VIP & Bonus opportunities, 30 day cookies'." },
  },
  {
    slug: "bayla-skin-affiliate-program",
    brandName: "Bayla Skin",
    name: "Bayla Skin Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Skincare",
    description:
      "Bayla Skin is an Indian skincare brand with superfood-infused, science-backed formulations. Its affiliate program, run on GoAffPro, is free to join, provides linking tools, and pays a commission on all qualifying purchases from successful referrals.",
    websiteUrl: "https://bayla.in",
    programUrl: "https://bayla.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 20% on successful referrals",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "bayla-skin",
    sources: { checkedOn: CHECKED, urls: ["https://bayla.goaffpro.com/"], notes: "Portal (©bayla.in): 'Get up to 20% in commissions'." },
  },
  {
    slug: "rasayanam-affiliate-program",
    brandName: "Rasayanam",
    name: "Rasayanam Affiliate Program",
    programType: "AFFILIATE",
    category: "Personal Care",
    subcategory: "Ayurveda & wellness",
    description:
      "Rasayanam is an Indian Ayurvedic wellness brand selling herbal supplements and natural health products. Its affiliate program, run on GoAffPro, is free to join and pays a commission on all qualifying purchases from your successful referrals.",
    websiteUrl: "https://rasayanam.in",
    programUrl: "https://rasayanam.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% on successful referrals",
    geography: "India",
    bestFor: ["Lifestyle creators", "Fitness creators"],
    logo: "rasayanam",
    sources: { checkedOn: CHECKED, urls: ["https://rasayanam.goaffpro.com/"], notes: "Portal (©rasayanam.in): 'Earn up to 10% commission'." },
  },
  {
    slug: "giri-affiliate-program",
    brandName: "Giri",
    name: "Giri India Affiliate Program",
    programType: "AFFILIATE",
    category: "Other",
    subcategory: "Devotional & cultural goods",
    description:
      "Giri is an Indian retailer of products for Indian culture and tradition, including idols, pooja items, books and devotional goods. Its affiliate program pays a commission on total referral sales made through your affiliate link or coupon code.",
    websiteUrl: "https://giri.in",
    programUrl: "https://af.uppromote.com/giri/register",
    networkName: "UpPromote",
    commissionType: "PERCENTAGE",
    commissionDescription: "5% of total referral sales",
    cookieDurationDays: 30,
    geography: "India",
    bestFor: ["Lifestyle creators", "General creators"],
    logo: "giri",
    sources: { checkedOn: CHECKED, urls: ["https://af.uppromote.com/giri/register"], notes: "Registration form: 30 cookie days, 5% of referral sales." },
  },
  {
    slug: "hammer-affiliate-program",
    brandName: "Hammer",
    name: "Hammer Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Audio & wearables",
    description:
      "Hammer is an Indian consumer electronics brand selling earbuds, headphones, speakers and smartwatches. Its affiliate program, run on GoAffPro, is free to join and pays a commission on successful referrals from your links.",
    websiteUrl: "https://hammeronline.in",
    programUrl: "https://hammeronline.goaffpro.com/",
    networkName: "GoAffPro",
    commissionType: "VARIES",
    commissionDescription: "Up to 10% per successful referral",
    geography: "India",
    bestFor: ["Tech creators"],
    logo: "hammer",
    sources: { checkedOn: CHECKED, urls: ["https://hammeronline.goaffpro.com/"], notes: "Portal (©hammeronline.in): 'Earn Upto 10% commission'." },
  },
  {
    slug: "urban-monkey-affiliate-program",
    brandName: "Urban Monkey",
    name: "Urban Monkey Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Streetwear & headwear",
    description:
      "Urban Monkey is an Indian streetwear brand known for caps, headwear and apparel. Its affiliate program pays a commission on total referral sales made through your affiliate link, with product links and size preferences collected at signup.",
    websiteUrl: "https://www.urbanmonkey.com",
    programUrl: "https://af.uppromote.com/urbanmonkey/register",
    networkName: "UpPromote",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% of total referral sales",
    cookieDurationDays: 30,
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "urban-monkey",
    sources: { checkedOn: CHECKED, urls: ["https://af.uppromote.com/urbanmonkey/register"], notes: "Registration form: 10.00%, cookie 30 days." },
  },
  {
    slug: "vahdam-india-affiliate-program",
    brandName: "VAHDAM India",
    name: "VAHDAM India Affiliate Program",
    programType: "AFFILIATE",
    category: "Food",
    subcategory: "Tea & wellness",
    description:
      "VAHDAM India is an Indian tea and wellness brand selling teas, herbal infusions, supplements and gifts. Its India affiliate program gives you banners, coupon codes and text links to promote products and pays a commission on each customer order.",
    websiteUrl: "https://www.vahdam.in",
    programUrl: "https://www.vahdam.in/pages/affiliate",
    commissionType: "VARIES",
    commissionDescription: "4%–20% per customer order",
    geography: "India",
    bestFor: ["Food creators", "Lifestyle creators"],
    logo: "vahdam-india",
    sources: { checkedOn: CHECKED, urls: ["https://www.vahdam.in/pages/affiliate"], notes: "'earn a 4%-20% commission per customer order'." },
  },
  {
    slug: "kica-brand-ambassador-program",
    brandName: "Kica",
    name: "Kica Chica Brand Ambassador Program",
    programType: "INFLUENCER",
    category: "Fitness",
    subcategory: "Women's activewear",
    description:
      "Kica is an Indian women's activewear brand. The Kica Chica Brand Ambassador Program looks for women passionate about fitness and wellness who want to build a community; you apply with a short form on Kica's site and the team reaches out.",
    websiteUrl: "https://kicaactive.com",
    programUrl: "https://kicaactive.com/pages/kica-chica-brand-ambassador-program",
    requirements: "Women passionate about fitness and community building; apply through the form.",
    geography: "India",
    bestFor: ["Fitness creators"],
    logo: "kica",
    sources: { checkedOn: CHECKED, urls: ["https://kicaactive.com/pages/kica-chica-brand-ambassador-program"], notes: "Ambassador application form with eligibility; no commission stated." },
  },
  {
    slug: "divine-hindu-brand-ambassador-program",
    brandName: "Divine Hindu",
    name: "Divine Hindu Brand Ambassador Program",
    programType: "CREATOR_AFFILIATE",
    category: "Lifestyle",
    subcategory: "Spiritual jewellery & malas",
    description:
      "Divine Hindu is an Indian brand of spiritual jewellery, malas and devotional lifestyle products. Its Brand Ambassador Program pays creators a commission on every delivered order through their link or code, gives followers 10% off, and pays out twice a week.",
    websiteUrl: "https://www.divinehindu.in",
    programUrl: "https://www.divinehindu.in/pages/brand-ambassador-program",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% on delivered orders (followers get 10% off)",
    requirements: "At least 1,500 followers on Instagram or YouTube; payouts every Tuesday and Saturday to UPI or bank.",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "divine-hindu",
    sources: { checkedOn: CHECKED, urls: ["https://www.divinehindu.in/pages/brand-ambassador-program"], notes: "'flat 10% commission on every delivered order'; minimum 1,500 followers." },
  },
  {
    slug: "sanfe-affiliate-program",
    brandName: "Sanfe",
    name: "Sanfe Affiliate Program",
    programType: "AFFILIATE",
    category: "Personal Care",
    subcategory: "Women's hygiene",
    description:
      "Sanfe is an Indian personal care brand focused on women's hygiene and body care products. Its affiliate program page takes applications from creators through a form asking for social profiles, so the brand can onboard partners who promote its products for commission.",
    websiteUrl: "https://sanfe.in",
    programUrl: "https://sanfe.in/pages/affiliate-program",
    requirements: "Apply with your Instagram (required) and other social profiles.",
    geography: "India",
    bestFor: ["Beauty creators", "Lifestyle creators"],
    logo: "sanfe",
    sources: { checkedOn: CHECKED, urls: ["https://sanfe.in/pages/affiliate-program"], notes: "Rendered page: affiliate application form; title 'Earn Commission Promoting Sanfe Products'; rate not stated." },
  },
  {
    slug: "kay-beauty-affiliate-community",
    brandName: "Kay Beauty",
    name: "Kay Affiliate Community",
    programType: "CREATOR_AFFILIATE",
    category: "Beauty",
    subcategory: "Makeup",
    description:
      "Kay Beauty is an Indian makeup brand co-founded by Katrina Kaif. The Kay Affiliate Community invites creators to apply with their Instagram profile and portfolio through a form on Kay Beauty's site; the brand reviews applications to join the community.",
    websiteUrl: "https://www.kaybeauty.com",
    programUrl: "https://www.kaybeauty.com/pages/affiliate-form",
    requirements: "Apply with your Instagram profile and portfolio.",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "kay-beauty",
    sources: { checkedOn: CHECKED, urls: ["https://www.kaybeauty.com/pages/affiliate-form"], notes: "Rendered page: 'Apply to be a part of our amazing community!'; terms not stated." },
  },
  {
    slug: "hobby-india-affiliate-program",
    brandName: "Hobby India",
    name: "Hobby India Affiliate Program",
    programType: "AFFILIATE",
    category: "Other",
    subcategory: "Art & craft supplies",
    description:
      "Hobby India is an Indian online store for art and craft supplies run by Hobby Decor Pvt Ltd. Its affiliate program offers linking tools for networks, content sites and influencers, and pays a commission on all qualifying purchases from your referrals.",
    websiteUrl: "https://hobbyindia.store",
    programUrl: "https://hobbyindia.store/pages/affiliates",
    networkName: "GoAffPro",
    commissionType: "PERCENTAGE",
    commissionDescription: "Flat 5% on qualifying referrals",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "hobby-india",
    sources: { checkedOn: CHECKED, urls: ["https://hobbyindia.store/pages/affiliates"], notes: "'Get Flat 5% in commissions on successful referrals'." },
  },
  {
    slug: "bummer-referral-program",
    brandName: "Bummer",
    name: "Bummer Referral Program",
    programType: "REFERRAL",
    category: "Fashion",
    subcategory: "Innerwear",
    description:
      "Bummer is an Indian innerwear and loungewear brand. Its referral program lets existing customers share a referral link; when a new customer completes a delivered first purchase of at least ₹999, the referrer earns a reward.",
    websiteUrl: "https://bummer.in",
    programUrl: "https://bummer.in/pages/policy-for-bummer-referral-program",
    commissionType: "FIXED",
    commissionDescription: "₹200 referral reward (friend's order ₹999+)",
    requirements: "For customers with an active Bummer account; referees must be new customers.",
    geography: "India",
    bestFor: ["Fashion creators", "General creators"],
    logo: "bummer",
    sources: { checkedOn: CHECKED, urls: ["https://bummer.in/pages/policy-for-bummer-referral-program"], notes: "Title 'Refer & Earn ₹200'; minimum order ₹999; delivered, not returned." },
  },
  {
    slug: "mamaearth-refer-and-earn",
    brandName: "Mamaearth",
    name: "Mamaearth Refer and Earn",
    programType: "REFERRAL",
    category: "Beauty",
    subcategory: "Personal care",
    description:
      "Mamaearth is an Indian personal care brand selling skincare, haircare and baby care products. Its Refer and Earn program gives your friend wallet cash when they sign up and credits you wallet cash after their first order is delivered.",
    websiteUrl: "https://mamaearth.in",
    programUrl: "https://mamaearth.in/pages/refer",
    commissionType: "FIXED",
    commissionDescription: "₹100 MamaCash each for you and your friend",
    geography: "India",
    bestFor: ["Beauty creators", "Parenting creators"],
    logo: "mamaearth",
    sources: { checkedOn: CHECKED, urls: ["https://mamaearth.in/pages/refer"], notes: "'Refer a friend and you both get ₹100'." },
  },
  {
    slug: "the-derma-co-refer-and-earn",
    brandName: "The Derma Co",
    name: "The Derma Co Refer and Earn",
    programType: "REFERRAL",
    category: "Beauty",
    subcategory: "Skincare",
    description:
      "The Derma Co is an Indian active-ingredient skincare brand. Its Refer and Earn program gives a friend DermaCash when they sign up with your link and credits you DermaCash once their first order is delivered.",
    websiteUrl: "https://thedermaco.com",
    programUrl: "https://thedermaco.com/pages/refer",
    commissionType: "FIXED",
    commissionDescription: "₹100 DermaCash each for you and your friend",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "the-derma-co",
    sources: { checkedOn: CHECKED, urls: ["https://thedermaco.com/pages/refer"], notes: "'Refer a friend and you both get ₹100'." },
  },
  {
    slug: "innovist-referral-program",
    brandName: "Innovist",
    name: "Innovist Referral Program",
    programType: "REFERRAL",
    category: "Beauty",
    subcategory: "Hair & skincare",
    description:
      "Innovist is an Indian beauty company behind brands such as Bare Anatomy, Chemist at Play and Sunscoop. Its referral program rewards both you and your friend with iCash after the friend's eligible first purchase through your link is delivered.",
    websiteUrl: "https://innovist.com",
    programUrl: "https://innovist.com/pages/referrals-page",
    commissionType: "FIXED",
    commissionDescription: "100 iCash each after the friend's order is delivered",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "innovist",
    sources: { checkedOn: CHECKED, urls: ["https://innovist.com/pages/referrals-page"], notes: "'you both receive 100 iCash after their order is delivered'." },
  },
  {
    slug: "traya-referral-program",
    brandName: "Traya",
    name: "Traya Referral Program",
    programType: "REFERRAL",
    category: "Personal Care",
    subcategory: "Hair care",
    description:
      "Traya is an Indian hair-fall treatment brand combining Ayurveda, dermatology and nutrition. Its referral program gives your friend a discount on their first month's kit and gives you a discount code after their kit is delivered.",
    websiteUrl: "https://traya.health",
    programUrl: "https://traya.health/pages/referral",
    commissionType: "FIXED",
    commissionDescription: "₹500 off for your friend; ₹500 code for you",
    requirements: "Customers with at least one delivered order; referees must be first-time customers.",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "traya",
    sources: { checkedOn: CHECKED, urls: ["https://traya.health/pages/referral"], notes: "₹500 coupon each; first month kit only." },
  },
  {
    slug: "easemytrip-refer-and-earn",
    brandName: "EaseMyTrip",
    name: "EaseMyTrip Refer and Earn",
    programType: "REFERRAL",
    category: "Travel",
    subcategory: "Online travel",
    description:
      "EaseMyTrip is an Indian online travel company for flights, hotels, buses and holidays. Its Refer and Earn program credits wallet money when friends you invite to the app sign up and book travel, with separate rewards for flight, hotel and bus bookings.",
    websiteUrl: "https://www.easemytrip.com",
    programUrl: "https://www.easemytrip.com/refer",
    commissionType: "VARIES",
    commissionDescription: "Up to ₹500 per booking type, up to ₹2,000 in EMT wallet",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "easemytrip",
    sources: { checkedOn: CHECKED, urls: ["https://www.easemytrip.com/refer"], notes: "'Invite your friends & earn up to ₹2000'; up to ₹500 each for flight, hotel, bus." },
  },
  {
    slug: "the-bear-house-referral-program",
    brandName: "The Bear House",
    name: "The Bear House Referral Program",
    programType: "REFERRAL",
    category: "Fashion",
    subcategory: "Menswear",
    description:
      "The Bear House is an Indian menswear brand selling shirts, trousers and casual wear. Its referral program is open to anyone: share your referral link, and when your friend's order through it is delivered, you receive a payout.",
    websiteUrl: "https://thebearhouse.com",
    programUrl: "https://thebearhouse.com/pages/refer-and-earn",
    requirements: "Anyone can join the referral program.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "the-bear-house",
    sources: { checkedOn: CHECKED, urls: ["https://thebearhouse.com/pages/refer-and-earn"], notes: "Payout after the referred order is delivered; amount not stated." },
  },
  {
    slug: "comet-referral-program",
    brandName: "Comet",
    name: "Comet Referral Program",
    programType: "REFERRAL",
    category: "Fashion",
    subcategory: "Sneakers",
    description:
      "Comet is an Indian sneaker brand. Its referral program lets customers who have bought a pair share a code with new friends; both of you get money off your next pair once the friend uses it.",
    websiteUrl: "https://www.wearcomet.com",
    programUrl: "https://www.wearcomet.com/pages/referral",
    commissionType: "FIXED",
    commissionDescription: "₹800 off for you and your friend",
    requirements: "Buy your first Comet pair to start referring; rewards are for new customers only.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "comet",
    sources: { checkedOn: CHECKED, urls: ["https://www.wearcomet.com/pages/referral"], notes: "'you both get ₹800 off'." },
  },
  {
    slug: "house-of-chikankari-referral-program",
    brandName: "House of Chikankari",
    name: "House of Chikankari Refer and Earn",
    programType: "REFERRAL",
    category: "Fashion",
    subcategory: "Chikankari ethnic wear",
    description:
      "House of Chikankari is an Indian brand of handcrafted Lucknowi chikankari clothing. Its Refer and Earn program gives your friend money off a first order of ₹1,000 or more and credits you reward points for each successful referral.",
    websiteUrl: "https://www.houseofchikankari.in",
    programUrl: "https://www.houseofchikankari.in/pages/referrals",
    commissionType: "FIXED",
    commissionDescription: "20,000 points per referral; friend gets ₹200 off",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "house-of-chikankari",
    sources: { checkedOn: CHECKED, urls: ["https://www.houseofchikankari.in/pages/referrals"], notes: "'Each successful referral will earn you 20,000 Points and your friend ₹200 off'; ₹1,000 minimum." },
  },
  {
    slug: "livpure-refer-and-earn",
    brandName: "Livpure",
    name: "Livpure Refer and Earn",
    programType: "REFERRAL",
    category: "Home",
    subcategory: "Water purifiers & appliances",
    description:
      "Livpure is an Indian brand of water purifiers, air coolers and home appliances. Its Refer and Earn page lets customers submit a friend's details; the referred friend receives an extra 5% off their first purchase.",
    websiteUrl: "https://livpure.com",
    programUrl: "https://livpure.com/pages/refer-and-earn",
    geography: "India",
    bestFor: ["Home creators"],
    logo: "livpure",
    sources: { checkedOn: CHECKED, urls: ["https://livpure.com/pages/refer-and-earn"], notes: "Referee gets extra 5% off; referrer reward not stated." },
  },
  {
    slug: "upakarma-refer-and-earn",
    brandName: "Upakarma Ayurveda",
    name: "Upakarma Ayurveda Refer and Earn",
    programType: "REFERRAL",
    category: "Personal Care",
    subcategory: "Ayurveda & wellness",
    description:
      "Upakarma Ayurveda is an Indian Ayurvedic wellness brand. Its Refer and Earn program gives you a referral link from your dashboard and pays a commission on the total value of orders placed by people you refer.",
    websiteUrl: "https://upakarma.com",
    programUrl: "https://upakarma.com/pages/refer-and-earn",
    commissionType: "PERCENTAGE",
    commissionDescription: "10% of the referred order value",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "upakarma-ayurveda",
    sources: { checkedOn: CHECKED, urls: ["https://upakarma.com/pages/refer-and-earn"], notes: "'you will earn 10% as commission of the total order value'." },
  },
  {
    slug: "lohono-infinity-referral-programme",
    brandName: "Lohono Stays",
    name: "Lohono Infinity Referral Programme",
    programType: "REFERRAL",
    category: "Travel",
    subcategory: "Luxury villas",
    description:
      "Lohono Stays is an Indian luxury villa rental company with homes in Goa and other destinations. Its Infinity Referral Programme awards members points when a referred guest completes a stay, redeemable on future bookings with no referral limit.",
    websiteUrl: "https://www.lohono.com",
    programUrl: "https://www.lohono.com/refer",
    commissionType: "VARIES",
    commissionDescription: "Up to 10,000 Infinity Points per referral (1 point = ₹1)",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "lohono-stays",
    sources: { checkedOn: CHECKED, urls: ["https://www.lohono.com/refer"], notes: "'Get up to 10,000 Infinity Points per referral'; 1 point = 1 rupee." },
  },
  {
    slug: "floweraura-refer-and-earn",
    brandName: "FlowerAura",
    name: "FlowerAura Refer and Earn",
    programType: "REFERRAL",
    category: "Other",
    subcategory: "Gifting & flowers",
    description:
      "FlowerAura is an Indian online gifting company delivering flowers, cakes and gifts. Its Refer and Earn program gives signed-in customers a referral link to share with friends and family, unlocking rewards when the referral coupons are used.",
    websiteUrl: "https://www.floweraura.com",
    programUrl: "https://www.floweraura.com/refer-and-earn",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "floweraura",
    sources: { checkedOn: CHECKED, urls: ["https://www.floweraura.com/refer-and-earn"], notes: "Referral link after login; reward amount not stated on the public page." },
  },
  {
    slug: "zoomin-refer-and-earn",
    brandName: "Zoomin",
    name: "Zoomin Refer and Earn",
    programType: "REFERRAL",
    category: "Other",
    subcategory: "Photo gifts & prints",
    description:
      "Zoomin is an Indian personalised photo gifts and printing company. Its referral program gives friends money off their first order and credits your Zoomin Rewards account with points after their order, with no limit on referrals.",
    websiteUrl: "https://www.zoomin.com",
    programUrl: "https://www.zoomin.com/refer-code",
    commissionType: "FIXED",
    commissionDescription: "Points worth ₹100 for you; friend gets ₹150 off",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "zoomin",
    sources: { checkedOn: CHECKED, urls: ["https://www.zoomin.com/refer-code"], notes: "'Rs.150 off on their first order'; points equal to Rs.100 credited." },
  },
  {
    slug: "the-pant-project-referral-program",
    brandName: "The Pant Project",
    name: "The Pant Project Referral Program",
    programType: "REFERRAL",
    category: "Fashion",
    subcategory: "Trousers",
    description:
      "The Pant Project is an Indian brand of made-to-measure and ready-to-wear trousers. Its referral program is open to anyone: share your referral link, and when your friend's order through it is delivered, you receive a payout.",
    websiteUrl: "https://pantproject.com",
    programUrl: "https://pantproject.com/pages/referral-program",
    requirements: "Anyone can join the referral program.",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "the-pant-project",
    sources: { checkedOn: CHECKED, urls: ["https://pantproject.com/pages/referral-program"], notes: "Payout after delivery; amount not stated." },
  },
  {
    slug: "cult-fit-referral-program",
    brandName: "cult.fit",
    name: "cult.fit Referral Program",
    programType: "REFERRAL",
    category: "Fitness",
    subcategory: "Gyms & fitness classes",
    description:
      "cult.fit is an Indian fitness company offering gyms, group workouts and home fitness. Its referral program lets selected users earn Fitcash or free days as a membership extension or access pass when they refer friends who are new to cult.fit.",
    websiteUrl: "https://www.cult.fit",
    programUrl: "https://support.cult.fit/support/solutions/articles/25000018912-what-s-the-cult-fit-referral-program-",
    requirements: "Selected cult.fit users; valid in India only; referred friends get a discount on their first purchase.",
    geography: "India",
    bestFor: ["Fitness creators"],
    logo: "cult-fit",
    sources: { checkedOn: CHECKED, urls: ["https://support.cult.fit/support/solutions/articles/25000018912-what-s-the-cult-fit-referral-program-"], notes: "Fitcash or membership extension; India only." },
  },
  {
    slug: "aqualogica-refer-and-earn",
    brandName: "Aqualogica",
    name: "Aqualogica Refer and Earn",
    programType: "REFERRAL",
    category: "Beauty",
    subcategory: "Skincare",
    description:
      "Aqualogica is an Indian skincare brand built around hydration-focused formulas. Its Refer and Earn program gives your friend a discount on their order through your link and credits you AquaCash once their order is delivered.",
    websiteUrl: "https://aqualogica.in",
    programUrl: "https://aqualogica.in/pages/refer",
    commissionType: "FIXED",
    commissionDescription: "₹100 AquaCash for you; friend gets 30% off",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "aqualogica",
    sources: { checkedOn: CHECKED, urls: ["https://aqualogica.in/pages/refer"], notes: "'you get ₹100 AquaCash once their order gets delivered'; friend gets flat 30% off." },
  },
  {
    slug: "ajio-affiliate-program",
    brandName: "AJIO",
    name: "AJIO Affiliate Program",
    programType: "AFFILIATE",
    category: "E-commerce",
    subcategory: "Fashion marketplace",
    description:
      "AJIO is Reliance Retail's Indian online fashion and lifestyle store, selling clothing, footwear and accessories across ethnic, western and international labels. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.ajio.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/ajio-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "ajio",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/ajio-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "aramya-affiliate-program",
    brandName: "Aramya",
    name: "Aramya Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Women's ethnic wear",
    description:
      "Aramya is an Indian women's ethnic wear brand selling breathable cotton kurtas, kurta sets and dresses in sizes up to 10XL. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://aramya.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/aramya-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "aramya",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/aramya-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "cleartrip-affiliate-program",
    brandName: "Cleartrip",
    name: "Cleartrip Affiliate Program",
    programType: "AFFILIATE",
    category: "Travel",
    subcategory: "Online travel",
    description:
      "Cleartrip is an Indian online travel company, headquartered in Mumbai, for flight, train and hotel bookings and holiday packages. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.cleartrip.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/cleartrip-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "cleartrip",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/cleartrip-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "controlz-affiliate-program",
    brandName: "ControlZ",
    name: "ControlZ Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Refurbished smartphones",
    description:
      "ControlZ is an Indian company selling certified refurbished iPhones and Samsung phones, renewed in its own facility and sold with a warranty. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://controlz.world",
    programUrl: "https://www.admitad.com/en-in/store/offers/controlz-world-cps-in/",
    networkName: "Admitad",
    cookieDurationDays: 7,
    geography: "India",
    bestFor: ["Tech creators"],
    logo: "controlz",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/controlz-world-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "croma-affiliate-program",
    brandName: "Croma",
    name: "Croma Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Electronics retail",
    description:
      "Croma is the Tata Group's Indian consumer electronics and durables retailer, with large-format stores and an online store. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.croma.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/croma-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Tech creators"],
    logo: "croma",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/croma-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "dot-and-key-affiliate-program",
    brandName: "Dot & Key",
    name: "Dot & Key Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Skincare",
    description:
      "Dot & Key is an Indian skincare brand that combines natural ingredients with clinically tested formulations for everyday skin concerns. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.dotandkey.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/dotkey-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "dot-key",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/dotkey-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "firstcry-affiliate-program",
    brandName: "FirstCry",
    name: "FirstCry Affiliate Program",
    programType: "AFFILIATE",
    category: "Baby Products",
    subcategory: "Baby & kids store",
    description:
      "FirstCry is an Indian online and offline store for baby and kids products, from diapers and feeding to toys, clothing and school needs. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.firstcry.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/firstcry-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Parenting creators"],
    logo: "firstcry",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/firstcry-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "noise-affiliate-program",
    brandName: "Noise",
    name: "Noise Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Audio & wearables",
    description:
      "Noise is an Indian lifestyle technology brand selling smartwatches, earbuds, headphones and smart rings. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.gonoise.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/gonoise-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Tech creators", "Fitness creators"],
    logo: "noise",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/gonoise-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "gostops-affiliate-program",
    brandName: "goSTOPS",
    name: "goSTOPS Affiliate Program",
    programType: "AFFILIATE",
    category: "Travel",
    subcategory: "Hostels & budget stays",
    description:
      "goSTOPS is an Indian chain of backpacker hostels and budget stays across more than 30 destinations, founded in 2014. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://gostops.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/gostops-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "gostops",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/gostops-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "havells-affiliate-program",
    brandName: "Havells",
    name: "Havells Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Home appliances & electricals",
    description:
      "Havells is an Indian manufacturer of electrical equipment and home appliances, including fans, lighting, kitchen appliances and personal care products. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://havells.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/havells-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Home creators", "Tech creators"],
    logo: "havells",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/havells-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "kama-ayurveda-affiliate-program",
    brandName: "Kama Ayurveda",
    name: "Kama Ayurveda Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Ayurvedic beauty",
    description:
      "Kama Ayurveda is an Indian brand of Ayurvedic and natural beauty and wellness products, also used by leading hotels and spas. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.kamaayurveda.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/kama-ayurveda-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "kama-ayurveda",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/kama-ayurveda-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "lenskart-affiliate-program",
    brandName: "Lenskart",
    name: "Lenskart Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Eyewear",
    description:
      "Lenskart is an Indian eyewear company selling prescription glasses, sunglasses and contact lenses online and in stores. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.lenskart.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/lenskart-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators", "Lifestyle creators"],
    logo: "lenskart",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/lenskart-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "libas-affiliate-program",
    brandName: "Libas",
    name: "Libas Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Women's ethnic wear",
    description:
      "Libas is an Indian women's ethnic wear brand founded in 1985, launching new kurta, suit and co-ord collections every few weeks. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.libas.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/libas-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "libas",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/libas-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "milton-affiliate-program",
    brandName: "Milton",
    name: "Milton Affiliate Program",
    programType: "AFFILIATE",
    category: "Home",
    subcategory: "Kitchenware & bottles",
    description:
      "Milton is an Indian homeware and kitchenware brand known for bottles, flasks, insulated containers and lunch boxes. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.milton.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/milton-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Home creators", "Food creators"],
    logo: "milton",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/milton-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "mivi-affiliate-program",
    brandName: "Mivi",
    name: "Mivi Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Audio",
    description:
      "Mivi is an Indian consumer electronics brand that designs and makes wireless earbuds, headphones, neckbands and speakers in India. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.mivi.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/mivi-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Tech creators"],
    logo: "mivi",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/mivi-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "myntra-affiliate-program",
    brandName: "Myntra",
    name: "Myntra Affiliate Program",
    programType: "AFFILIATE",
    category: "E-commerce",
    subcategory: "Fashion marketplace",
    description:
      "Myntra is an Indian online fashion and lifestyle marketplace headquartered in Bengaluru, selling clothing, footwear, beauty and accessories. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.myntra.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/myntra-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators", "Beauty creators"],
    logo: "myntra",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/myntra-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "neemans-affiliate-program",
    brandName: "Neeman's",
    name: "Neeman's Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Comfort footwear",
    description:
      "Neeman's is an Indian footwear brand making comfortable sneakers, slip-ons and casual shoes from natural materials. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://neemans.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/neemans-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "neeman-s",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/neemans-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "nilkamal-affiliate-program",
    brandName: "Nilkamal",
    name: "Nilkamal Affiliate Program",
    programType: "AFFILIATE",
    category: "Home",
    subcategory: "Furniture",
    description:
      "Nilkamal is an Indian manufacturer of home and office furniture, mattresses and moulded plastic products. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.nilkamalfurniture.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/nilkamal-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Home creators"],
    logo: "nilkamal",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/nilkamal-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "nveda-affiliate-program",
    brandName: "Nveda",
    name: "Nveda Affiliate Program",
    programType: "AFFILIATE",
    category: "Food",
    subcategory: "Ayurvedic & nutritional supplements",
    description:
      "Nveda is an Indian brand of nutritional and health supplements made with natural ingredients and Ayurvedic herbs. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://nveda.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/nveda-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fitness creators", "Lifestyle creators"],
    logo: "nveda",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/nveda-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "oziva-affiliate-program",
    brandName: "OZiva",
    name: "OZiva Affiliate Program",
    programType: "AFFILIATE",
    category: "Food",
    subcategory: "Plant-based nutrition",
    description:
      "OZiva is an Indian clean-label nutrition brand combining modern nutrition science with Ayurveda in protein, beauty and wellness supplements. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.oziva.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/oziva-new-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fitness creators", "Beauty creators"],
    logo: "oziva",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/oziva-new-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "palmonas-affiliate-program",
    brandName: "Palmonas",
    name: "Palmonas Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Demi-fine jewellery",
    description:
      "Palmonas is an Indian demi-fine jewellery brand selling thick 18k gold-plated pieces for everyday wear. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://palmonas.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/palmonas-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "palmonas",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/palmonas-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "pepperfry-affiliate-program",
    brandName: "Pepperfry",
    name: "Pepperfry Affiliate Program",
    programType: "AFFILIATE",
    category: "Home",
    subcategory: "Furniture & decor",
    description:
      "Pepperfry is an Indian online marketplace for furniture, home decor and furnishings. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.pepperfry.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/pepperfry-web-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Home creators"],
    logo: "pepperfry",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/pepperfry-web-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "sheetal-batra-affiliate-program",
    brandName: "Sheetal Batra",
    name: "Sheetal Batra Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Designer ethnic wear",
    description:
      "Sheetal Batra is an Indian designer label of luxurious ethnic wear for women that revives traditional designs with a contemporary touch. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://sheetalbatra.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/sheetal-batra-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "sheetal-batra",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/sheetal-batra-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "shyaway-affiliate-program",
    brandName: "Shyaway",
    name: "Shyaway Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Lingerie & nightwear",
    description:
      "Shyaway is an Indian online store for lingerie, nightwear, shapewear and swimwear for women. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.shyaway.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/shyaway-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "shyaway",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/shyaway-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "tanishq-affiliate-program",
    brandName: "Tanishq",
    name: "Tanishq Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Fine jewellery",
    description:
      "Tanishq is the Titan Company's Indian fine jewellery brand, selling gold, diamond and wedding jewellery. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.tanishq.co.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/tanishq-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "tanishq",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/tanishq-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "tata-cliq-affiliate-program",
    brandName: "Tata CLiQ",
    name: "Tata CLiQ Affiliate Program",
    programType: "AFFILIATE",
    category: "E-commerce",
    subcategory: "Online marketplace",
    description:
      "Tata CLiQ is the Tata Group's Indian online marketplace for fashion, electronics, home and luxury products. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.tatacliq.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/tatacliq-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators", "Tech creators"],
    logo: "tata-cliq",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/tatacliq-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "the-man-company-affiliate-program",
    brandName: "The Man Company",
    name: "The Man Company Affiliate Program",
    programType: "AFFILIATE",
    category: "Personal Care",
    subcategory: "Men's grooming",
    description:
      "The Man Company is an Indian men's grooming brand selling beard care, skincare, fragrances and gift sets made with essential oils. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.themancompany.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/themancompany-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Lifestyle creators"],
    logo: "the-man-company",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/themancompany-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "titan-affiliate-program",
    brandName: "Titan",
    name: "Titan Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Watches",
    description:
      "Titan is the Titan Company's Indian watch brand, selling analogue, smart and premium watches. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.titan.co.in",
    programUrl: "https://www.admitad.com/en-in/store/offers/titan-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators", "Lifestyle creators"],
    logo: "titan",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/titan-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "vegnonveg-affiliate-program",
    brandName: "VegNonVeg",
    name: "VegNonVeg Affiliate Program",
    programType: "AFFILIATE",
    category: "Fashion",
    subcategory: "Sneakers & streetwear",
    description:
      "VegNonVeg is an Indian multi-brand sneaker and streetwear store with stores and an online shop. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.vegnonveg.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/vegnonveg-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fashion creators"],
    logo: "vegnonveg",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/vegnonveg-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "vijay-sales-affiliate-program",
    brandName: "Vijay Sales",
    name: "Vijay Sales Affiliate Program",
    programType: "AFFILIATE",
    category: "Electronics",
    subcategory: "Electronics retail",
    description:
      "Vijay Sales is an Indian consumer electronics and home appliance retailer with stores and an online store. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.vijaysales.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/vijay-sales-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Tech creators"],
    logo: "vijay-sales",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/vijay-sales-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "abhibus-affiliate-program",
    brandName: "AbhiBus",
    name: "AbhiBus Affiliate Program",
    programType: "AFFILIATE",
    category: "Travel",
    subcategory: "Bus tickets",
    description:
      "AbhiBus is an Indian online platform for booking bus tickets across thousands of routes and operators. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.abhibus.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/abhibus-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "abhibus",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/abhibus-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "antinorm-affiliate-program",
    brandName: "Antinorm",
    name: "Antinorm Affiliate Program",
    programType: "AFFILIATE",
    category: "Beauty",
    subcategory: "Multifunctional makeup",
    description:
      "Antinorm is an Indian beauty brand founded by Aparna Saxena that makes multifunctional products formulated for Indian heat, humidity and pollution. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://antinorm.co",
    programUrl: "https://www.admitad.com/en-in/store/offers/antinorm-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Beauty creators"],
    logo: "antinorm",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/antinorm-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "air-india-affiliate-program",
    brandName: "Air India",
    name: "Air India Affiliate Program",
    programType: "AFFILIATE",
    category: "Travel",
    subcategory: "Airline",
    description:
      "Air India is India's flag carrier airline, flying domestic and international routes. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://www.airindia.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/air-india-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Travel creators"],
    logo: "air-india",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/air-india-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
  {
    slug: "wellbeing-nutrition-affiliate-program",
    brandName: "Wellbeing Nutrition",
    name: "Wellbeing Nutrition Affiliate Program",
    programType: "AFFILIATE",
    category: "Food",
    subcategory: "Health & beauty supplements",
    description:
      "Wellbeing Nutrition is an Indian brand of science-driven health and beauty supplements made with fresh, pure ingredients. Its affiliate programme runs on the Admitad network for India; you join on Admitad, where commission rates and programme terms are shown after you sign in.",
    websiteUrl: "https://wellbeingnutrition.com",
    programUrl: "https://www.admitad.com/en-in/store/offers/wellbeing-nutrition-cps-in/",
    networkName: "Admitad",
    geography: "India",
    bestFor: ["Fitness creators", "Beauty creators"],
    logo: "wellbeing-nutrition",
    sources: { checkedOn: CHECKED, urls: ["https://www.admitad.com/en-in/store/offers/wellbeing-nutrition-cps-in/"], notes: "Admitad India listing live, region India; commission shown only to registered publishers." },
  },
];
